FORMAT: 1A
HOST: https://vibes-music.herokuapp.com/

# Vibes

Vibes is a Music Store Application API that will bring an upcoming artiste to the limelight.

## Sign-up User [/api/v1/user/signup]

### Sign-up [POST]

+ Request (application/json)

        {
            "first_name": "John",
            "last_name": "Deo",
            "username": "John",
            "email": "JohnDeo@gmail.com",
            "password": "John",
            "password_confirmation": "John"
        }

+ Response 201 (application/json)

        [
            {
                "message": "User Created",
            }
        ]

## Sign-in User [/api/v1/user/]

### Sign-up [POST]

+ Request (application/json)

        {
            "email": "JohnDeo@gmail.com",
            "password": "John",
        }

+ Response 200 (application/json)

        [
            {
                "message": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk",
            }
        ]