FORMAT: 1A
HOST: https://vibes-music.herokuapp.com/

# Vibes

Vibes is a Music Store Application API that will bring an upcoming artiste to the limelight.

## Sign-up User [/api/v1/user/signup]

### Sign-up [POST]

+ Request (application/json)

        {
            "first_name": "John",
            "last_name": "Deo",
            "username": "John",
            "email": "JohnDeo@gmail.com",
            "password": "John",
            "password_confirmation": "John",
            "role": "user"
        }

+ Response 201 (application/json)

        [
            {
                "message": "User Created",
            }
        ]

## Sign-in User [/api/v1/user]

### Sign-up [POST]

+ Request (application/json)

        {
            "email": "JohnDeo@gmail.com",
            "password": "John",
        }

+ Response 200 (application/json)

        [
            {
                "message": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk",
            }
        ]
        
# Group Album Collection

## Create and Get all Albums [/api/v1/album]
Only an Artiste can Use these routes

### Create Album [POST]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk
    
    + Body
            
            {
                "name": "Love",
                "description": "Love rocks"
            }

+ Response 201 (application/json)

        [
            {
                "message": "Album Created",
            }
        ]

### Get all Albums [GET]
+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 201 (application/json)

        [
            {
                "name": "Love Hurts",
                "description": "Hurts deeply"
            },
            {
                "name": "Am Speeding",
                "description": "Speeding is coming"
            },
        ]

## Update and Delete Album [/api/v1/album/{id}]
### Update Album [PATCH]
+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk
    
    + Body
        
            {
                "name": "Love",
                "decription": "Love rocks",
            }
+ Response 200 (application/json)

        [
            {
                "name": "Love",
                "Description": "Love rocks"
            }
        ]
        
### Delete Album [DELETE]
+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk
    
+ Response 204 (application/json)

# Group Song Collection

## Create Song [/api/v1/song/album/{id}]
Only an Artiste can add a song. The song attribute requires a song upload

### Create Album [POST]

+ Request (form-data)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

    + Body

            {
                "name": "Love",
                "description": "Love rocks",
                "song": "This is a file upload",
                "genre": "rock",
            }

+ Response 201 (application/json)

        [
            {
                "message": "Song Created",
            }
        ]

## Download a Song [/api/v1/song/{song_id}]
### Download Song [GET]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 200 (application/json)


## Deledte a Song [/api/v1/song/{song_id}]
### Delete Song [DELETE]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 204 (application/json)


## All Songs [/api/v1/song]
### Get all Songs [GET]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 200 (application/json)

## Comment on a Song [/api/v1/song/{song_id}/comment]
### Add Comment [POST]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

    + Body

            {
                "name": "Love",
                "description": "Love rocks"
            }

+ Response 201 (application/json)

        [
            {
                "message": "Comment Created",
            }
        ]
    
# Group Search Collection

## Search all songs [/api/v1/search]
### Search Song [GET]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 201 (application/json)

        [
            {
                "id": 6,
                "name": "chad",
                "description": "work",
                "url": "audio/magnom_my_baby_lyric_video_ft_joey_b_mp3_63699 (1).mp3",
                "album_id": 2,
                "created_at": "2018-11-27 18:58:54",
                "updated_at": "2018-11-27 18:58:54",
                "genre": null,
                "album": {
                    "id": 2,
                    "name": "Love is true"
                }
            },
            {
                "id": 7,
                "name": "chad",
                "description": "work",
                "url": "audio/magnom_my_baby_lyric_video_ft_joey_b_mp3_63699 (1).mp3",
                "album_id": 2,
                "created_at": "2018-11-28 04:34:51",
                "updated_at": "2018-11-28 04:34:51",
                "genre": null,
                "album": {
                    "id": 2,
                    "name": "Love is true"
                }
            },
        ]
        


#Group Playlist Collection

## Create new Playlist [/api/v1/playlist]
### Create Playlist [POST]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk
    
    + Body
            
            {
                "name": "Love",
                "description": "Love rocks"
            }

+ Response 201 (application/json)

        [
            {
                "message": "Playlist Created",
            }
        ]

## Add Song to a Playlist [/api/v1/playlist/{playlist_id}/song/{song_id}]
### Create Playlist [POST]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 201 (application/json)

        [
            {
                "message": "Song added to playlist",
            }
        ]

## Share a Playlist [/api/v1/playlist/{playlist_id}/share]
### Share Playlist [POST]

+ Request (application/json)
    + Headers

            api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ2aWJlcyIsInN1YiI6OCwiaWF0IjoxNTQzMjIzODExLCJleHAiOjE1NDMyMjc0MTF9.rCJSePV5ByoAZ4St_b-UEx-pChu6m3nDnsd4Uw7HUXk

+ Response 201 (application/json)

        [
            {
                "id": 6,
                "name": "chad",
                "description": "work",
                "url": "audio/magnom_my_baby_lyric_video_ft_joey_b_mp3_63699 (1).mp3",
                "album_id": 2,
                "created_at": "2018-11-27 18:58:54",
                "updated_at": "2018-11-27 18:58:54"
            }
        ]